import { CheckCircle2, CloudRain, Eye, RadioTower, ShieldCheck, XCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { api } from "../../api/endpoints";
import type { FieldReport } from "../../api/types";
import { formatRelativeTime, titleCase } from "../../utils/format";
import { EmptyState, PanelHeading, StatusPill } from "./StatusUi";
import { useSkyGuard } from "../../hooks/useSkyGuard";

export default function CommunityIntelligence({ onNotify }: { onNotify: (message: string, tone?: "success" | "error") => void }) {
  const { fieldReports } = useSkyGuard();
  const [reports, setReports] = useState<FieldReport[]>([]); const [pending, setPending] = useState<string | null>(null);
  async function refresh() { try { setReports(await api.getAdminPublicReports()) } catch (c) { onNotify(c instanceof Error ? c.message : "Could not load community reports", "error") } }
  useEffect(() => { void refresh(); const id = window.setInterval(() => void refresh(), 10_000); return () => clearInterval(id) }, []);
  useEffect(() => setReports(fieldReports.filter((report) => report.source === "public_user")), [fieldReports]);
  async function act(report: FieldReport, action: "verify" | "monitor" | "reject" | "resolve") { setPending(report.id); try { await api.moderatePublicReport(report.id, action); await refresh(); onNotify(`Community report ${action === "verify" ? "verified" : action === "reject" ? "marked not supported" : action === "monitor" ? "kept under monitoring" : "resolved"}.`) } catch (c) { onNotify(c instanceof Error ? c.message : "Moderation failed", "error") } finally { setPending(null) } }
  const active = reports.filter(r => r.status === "active");
  return <div className="dashboard-view-stack community-admin"><div className="view-toolbar"><div><p className="panel-eyebrow">Public context · administrator review</p><h2>Community Intelligence</h2></div><StatusPill state={active.length ? "active" : "clear"} /></div><div className="field-summary-grid"><div><CloudRain /><span>Active Reports</span><strong>{active.length}</strong></div><div><Eye /><span>Awaiting Review</span><strong>{active.filter(r => r.verification_state === "pending_sensor_confirmation").length}</strong></div><div><ShieldCheck /><span>Sensor Supported</span><strong>{active.filter(r => ["partially_supported", "corroborated"].includes(r.verification_state)).length}</strong></div><div><RadioTower /><span>Manager Verified</span><strong>{reports.filter(r => r.verification_state === "manager_verified").length}</strong></div></div>{reports.length ? <div className="community-admin-grid">{reports.map(r => <article className="glass-card" key={r.id}><PanelHeading eyebrow="New public report" title={titleCase(r.category)} action={<StatusPill state={r.severity ?? "information"} />} /><p className="community-admin-observation">{r.observation}</p><div className="field-report-meta"><div><span>Near</span><strong>{r.location_label || "Prototype area"}</strong></div><div><span>Reported</span><strong>{formatRelativeTime(r.created_at)}</strong></div><div><span>Reporter</span><strong>Community User</strong></div><div><span>User confidence</span><strong>{titleCase(r.reporter_confidence)}</strong></div></div><div className="corroboration-block"><div><span>Sensor corroboration</span><strong>{titleCase(r.verification_state)}</strong><em>{r.corroboration_confidence}%</em></div><div className="corroboration-track"><span style={{ width: `${r.corroboration_confidence}%` }} /></div><p>{r.message}</p>{r.evidence.slice(0, 3).map(e => <small key={e}><CheckCircle2 />{e}</small>)}</div>{r.status === "active" && <div className="moderation-actions"><button disabled={pending === r.id} onClick={() => void act(r, "verify")}><ShieldCheck />Verify</button><button disabled={pending === r.id} onClick={() => void act(r, "monitor")}><Eye />Keep Monitoring</button><button disabled={pending === r.id} onClick={() => void act(r, "reject")}><XCircle />Not Supported</button><button disabled={pending === r.id} onClick={() => void act(r, "resolve")}><CheckCircle2 />Resolve</button></div>}</article>)}</div> : <EmptyState title="No public reports" message="Public observations will appear here in real time." />}</div>;
}
