import { patchJson, postJson, request } from "./client";
import type {
  AnomalyEvent,
  DashboardSummary,
  FieldReport,
  FieldReportCreatePayload,
  HealthResponse,
  IngestPayload,
  Metrics,
  MonitoringContext,
  NodeId,
  NodeListItem,
  NodeRecordsResponse,
  SensorHealth,
  SensorReading,
  TrustedReading,
  AdminSession,
  PublicReportPayload,
  MaintenanceStatus,
  MLStatus,
  SensorInventoryItem,
  SensorSpec,
  VisionEvent,
  VisionStatus,
} from "./types";

export const api = {
  login: (name: string, password: string) => postJson<AdminSession>("/auth/login", { name, password }),
  getAuthSession: () => request<Omit<AdminSession, "token">>("/auth/me"),
  logout: () => postJson<{ authenticated: false }>("/auth/logout"),
  getHealth: () => request<HealthResponse>("/health"),
  getMlStatus: () => request<MLStatus>("/ml/status"),
  getNodes: () => request<NodeListItem[]>("/nodes"),
  getLatest: (nodeId: NodeId) => request<SensorReading>(`/nodes/${encodeURIComponent(nodeId)}/latest`),
  getHistory: (nodeId: NodeId, limit = 100) =>
    request<SensorReading[]>(`/nodes/${encodeURIComponent(nodeId)}/history?limit=${limit}`),
  getRecords: (nodeId: NodeId, limit = 100) =>
    request<NodeRecordsResponse>(`/nodes/${encodeURIComponent(nodeId)}/records?limit=${limit}`),
  getEvents: (limit = 100) => request<AnomalyEvent[]>(`/events?limit=${limit}`),
  getSensorHealth: () => request<SensorHealth[]>("/sensor-health"),
  getNodeHealth: (nodeId: NodeId) => request<SensorHealth>(`/sensor-health/${encodeURIComponent(nodeId)}`),
  getTrustedStream: (limit = 100) => request<TrustedReading[]>(`/trusted-stream?limit=${limit}`),
  getMetrics: () => request<Metrics>("/metrics"),
  getDashboardSummary: () => request<DashboardSummary>("/dashboard/summary"),
  getPeerConsensus: (nodeId: NodeId) => request<Record<string, unknown>>(`/peer-consensus/${encodeURIComponent(nodeId)}`),
  getVisionStatus: () => request<VisionStatus[]>("/vision/status"),
  getVisionEvents: (limit = 100) => request<VisionEvent[]>(`/vision/events?limit=${limit}`),
  createVisionObservation: (nodeId: NodeId, detections: Array<{ type: string; confidence: number }>, source = "manual_camera") =>
    postJson<VisionEvent[]>("/vision/observations", { node_id: nodeId, source, detections }),
  getSensorSpecs: () => request<SensorSpec[]>("/sensor-specs"),
  getSensorInventory: (nodeId?: NodeId) => request<SensorInventoryItem[]>(nodeId ? `/sensor-inventory/${encodeURIComponent(nodeId)}` : "/sensor-inventory"),
  getMaintenance: (nodeId?: NodeId) => request<MaintenanceStatus[]>(nodeId ? `/maintenance/${encodeURIComponent(nodeId)}` : "/maintenance"),
  getMultiSourceContext: (nodeId: NodeId) => request<Record<string, unknown>>(`/multi-source-context/${encodeURIComponent(nodeId)}`),
  getFieldReports: (status?: string) => request<FieldReport[]>(`/field-reports${status ? `?status=${encodeURIComponent(status)}` : ""}`),
  getActiveFieldReports: () => request<FieldReport[]>("/field-reports/active"),
  getPublicReports: (status?: string) => request<FieldReport[]>(`/public/reports${status ? `?status=${encodeURIComponent(status)}` : ""}`),
  createPublicReport: (payload: PublicReportPayload) => postJson<FieldReport>("/public/reports", payload),
  getAdminPublicReports: () => request<FieldReport[]>("/admin/public-reports"),
  moderatePublicReport: (reportId: string, action: "verify" | "monitor" | "reject" | "resolve", notes?: string) =>
    postJson<FieldReport>(`/admin/public-reports/${encodeURIComponent(reportId)}/${action}`, { notes: notes ?? null }),
  getNearbyFieldReports: (nodeId: NodeId) => request<FieldReport[]>(`/field-reports/nearby/${encodeURIComponent(nodeId)}`),
  getFieldReport: (reportId: string) => request<FieldReport>(`/field-reports/${encodeURIComponent(reportId)}`),
  createFieldReport: (payload: FieldReportCreatePayload) => postJson<FieldReport>("/field-reports", payload),
  updateFieldReport: (reportId: string, payload: Partial<Pick<FieldReport, "status" | "severity" | "observation" | "notes">>) =>
    patchJson<FieldReport>(`/field-reports/${encodeURIComponent(reportId)}`, payload),
  resolveFieldReport: (reportId: string, notes?: string) =>
    postJson<FieldReport>(`/field-reports/${encodeURIComponent(reportId)}/resolve`, { notes: notes ?? null }),
  getMonitoringContexts: () => request<MonitoringContext[]>("/monitoring-context"),
  ingest: (payload: IngestPayload) => postJson<TrustedReading>("/ingest", payload),
};
